---
title: "Assignment 3"
author: "Tanjina Islam, Miguel Morales Expósito and Carlos Perales Liñan, group 12"
date: "13 March 2018"
output:
  pdf_document:
    fig_caption: yes
fontsize: 11pt
highlight: tango
---

## Exercise 1
We load the data from the data source
```{r}
# Add Code
```

### Task 1

```{r}
# Add Code
```

### Task 2

```{r}
# Add Code
```

### Task 3

```{r}
# Add Code
```

### Task 4

```{r}
# Add Code
```

### Task 5

```{r}
# Add Code
```

## Exercise 2
Exercise 2
```{r}
# Add Code
```

### Task 1

```{r}
# Add Code
```

### Task 2

```{r}
# Add Code
```

### Task 3

```{r}
# Add Code
```

### Task 4

```{r}
# Add Code
```

### Task 5

```{r}
# Add Code
```


### Task 6

```{r}
# Add Code
```

### Task 7

```{r}
# Add Code
```


## Exercise 3
Exercise 3
```{r}
# Add Code
```

### Task 1

```{r}
# Add Code
```

### Task 2

```{r}
# Add Code
```

### Task 3

```{r}
# Add Code
```

### Task 4

```{r}
# Add Code
```

## Exercise 4
Exercise 4
```{r}
# Add Code
```

### Task 1

```{r}
# Add Code
```

### Task 2

```{r}
# Add Code
```

### Task 3

```{r}
# Add Code
```

### Task 4

```{r}
# Add Code
```

## Exercise 5
Exercise 5
```{r}
# Add Code
```
### Task 1

```{r}
# Add Code
```

### Task 2

```{r}
# Add Code
```

### Task 3

```{r}
# Add Code
```

### Task 4

```{r}
# Add Code
```

## Exercise 6
Exercise 6
```{r}
# Add Code
```

### Task 1

```{r}
# Add Code
```

### Task 2

```{r}
# Add Code
```

### Task 3

```{r}
# Add Code
```

### Task 4

```{r}
# Add Code
```

### Task 5

```{r}
# Add Code
```

## Exercise 7
Exercise 7
```{r}
# Add Code
```

### Task a

```{r}
# Add Code
```

### Task b

```{r}
# Add Code
```

### Task c

```{r}
# Add Code
```

